/**
 * Created by py on 18-5-21.
 */
// Home
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const UPDATE_TAB = 'UPDATE_TAB'


// utils
export const TOAST = 'TOAST'
export const OPEN_TOAST = 'OPEN_TOAST'
export const CLOSE_TOAST = 'CLOSE_TOAST'

// middleware
export const SYNC_REDUCER_TO_ASYNC_STORAGE = 'SYNC_REDUCER_TO_ASYNC_STORAGE'
export const GET_REDUCER_FROM_ASYNC_STORAGE = 'GET_REDUCER_FROM_ASYNC_STORAGE'

//App布局
export const　GET_LAYOUT_BY_TAB = "GET_LAYOUT_BY_TAB"
export const　UPDATE_LAYOUT_BY_TAB = "UPDATE_LAYOUT_BY_TAB"

//节目
export const GET_PROGRAMS_BY_CATEGORYID = "GET_PROGRAMS_BY_CATEGORYID"
export const UPDATE_PROGRAMS_BY_CATEGORYID = "UPDATE_PROGRAMS_BY_CATEGORYID"
export const GET_PROGRAM_BY_ID = "GET_PROGRAM_BY_ID";

